Create the repository

diff --git a/pipeline.yml b/pipeline.yml
--- a/pipeline.yml
+++ b/pipeline.yml
@@ -45,12 +45,29 @@ jobs:
                         - |
                             set +x
                             echo ""
-                            echo "################"
-                            echo "# Hello  world #"
-                            echo "################"
+                            echo "########################"
+                            echo "# Downloading new RPMs #"
+                            echo "########################"
                             echo ""
                             set -x
 
+                            mkdir /tmp/new_rpms
+                            aws s3 sync s3://rpmrepo-1-ingest-b54e8/ /tmp//new_rpms/
+
+                            set +x
+                            echo ""
+                            echo "###########################"
+                            echo "# Updating the repository #"
+                            echo "###########################"
+                            echo ""
+                            set -x
+
+                            for rpm in /tmp/new_rpms/*.rpm; do
+                                distro=$(rpm -q --qf "%{RELEASE}\n" $rpm | grep -E -o 'fc[0-9]{2}|el[0-9]')
+                                [ -n "$distro" ] || (echo "Unable to figure out distro for $rpm"; exit 1)
+                                /rpm-s3/bin/rpm-s3 -b rpmrepo-1-43ybe46n6 -p "$distro/" -r eu-west-1 $rpm
+                            done
                 params:
-                    SSH_KEY: ((ssh-private))
+                    AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
+                    AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
 
